1.22.19 = https://github.com/Bearsampp/module-yarn/releases/download/2022.07.17/bearsampp-yarn-1.22.19-2022.07.17.7z
1.22.22 = https://github.com/Bearsampp/module-yarn/releases/download/2024.12.8/bearsampp-yarn-1.22.22-2024.12.8.7z
