#
# Copyright (c) 2021-2024 Bearsampp
# License:  GNU General Public License version 3 or later; see LICENSE.txt
# Author: Bear
# Website: https://bearsampp.com
# Github: https://github.com/Bearsampp
#

nodejs = https://github.com/Bearsampp/modules-untouched/releases/download/yarn-2022.07.17/node-v16.16.0-x64.msi
